# Generated by Django 4.0.4 on 2022-05-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='TaxPrice',
        ),
    ]
