# Generated by Django 4.0.4 on 2022-05-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_taxprice_order_taxprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='TaxPrice',
            new_name='taxPrice',
        ),
    ]
